title: Andrzej Więckowski
email: andrzej.wieckowski (at) pwr.edu.pl
description: >- # this means to ignore newlines until "baseurl:"
  Andrzej Więckowski homepage

encoding: "utf-8"

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://andywiecko.github.io" # the base hostname & protocol for your site, e.g. http://example.com

github_username:  andywiecko

# Build settings
markdown: kramdown
kramdown:
   # parse markdown inside block-level HTML tag
   parse_block_html: true

theme: minima
plugins:
  - jekyll-feed

footer-link-col: "#ff0000"

collections:
        teaching:
                output: false
                permaling: /teaching/:name


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
